/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Pet {
    id: bigint;
    age: bigint;
    name: string;
    petType: string;
}
export interface VaccinationEvent {
    vaccinationType: string;
    date: string;
    petId: bigint;
}
export interface Appointment {
    date: string;
    petId: bigint;
    purpose: string;
}
export interface Medication {
    endDate?: string;
    dosage: string;
    name: string;
    frequency: string;
    startDate: string;
}
export interface backendInterface {
    addAppointment(petId: bigint, date: string, purpose: string): Promise<void>;
    addMedication(petId: bigint, name: string, dosage: string, frequency: string, startDate: string, endDate: string | null): Promise<void>;
    addPet(name: string, age: bigint, petType: string): Promise<bigint>;
    addVaccinationEvent(petId: bigint, vaccinationType: string, date: string): Promise<void>;
    getAllPets(): Promise<Array<Pet>>;
    getAppointmentsByPet(petId: bigint): Promise<Array<Appointment>>;
    getMedicationsByPet(petId: bigint): Promise<Array<Medication>>;
    getPet(id: bigint): Promise<Pet | null>;
    getVaccinationsByPet(petId: bigint): Promise<Array<VaccinationEvent>>;
}
import type { Medication as _Medication, Pet as _Pet } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAppointment(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppointment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppointment(arg0, arg1, arg2);
            return result;
        }
    }
    async addMedication(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addPet(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPet(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPet(arg0, arg1, arg2);
            return result;
        }
    }
    async addVaccinationEvent(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVaccinationEvent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVaccinationEvent(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllPets(): Promise<Array<Pet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPets();
            return result;
        }
    }
    async getAppointmentsByPet(arg0: bigint): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByPet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByPet(arg0);
            return result;
        }
    }
    async getMedicationsByPet(arg0: bigint): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicationsByPet(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicationsByPet(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPet(arg0: bigint): Promise<Pet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPet(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPet(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVaccinationsByPet(arg0: bigint): Promise<Array<VaccinationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaccinationsByPet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaccinationsByPet(arg0);
            return result;
        }
    }
}
function from_candid_Medication_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medication): Medication {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pet]): Pet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [string];
    dosage: string;
    name: string;
    frequency: string;
    startDate: string;
}): {
    endDate?: string;
    dosage: string;
    name: string;
    frequency: string;
    startDate: string;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        dosage: value.dosage,
        name: value.name,
        frequency: value.frequency,
        startDate: value.startDate
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medication>): Array<Medication> {
    return value.map((x)=>from_candid_Medication_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
